### ISSUE TITLE
Prettier display

### ISSUE THREAD

**Issue by 4Denthusiast** [Terasology/FlowingLiquids#6]
Currently, the surface of every liquid block is flat, with small steps in between. There are many cases where generating more complicated surfaces (e.g. slopes instead of steps for gently sloped cases) would look nicer. Preferably, the current version of rendering should be kept too as an option.

**Comment by Cervator** [comment]
Another past suggestion has been implementing a sort of "sea foam" to cover otherwise ugly edges involved in water rendering. That would especially be useful in the case with the higher waves enabled (the water surface texture warps up and down so far you can see *under* it from land)

Simply throwing in some more shapes akin to flowing water in MC shouldn't be too effort intensive.

**Comment by 4Denthusiast** [comment]
Fixed in 0c5fd01. It's still not perfect (it can't smooth the surface between different block levels), but that would have been far more complicated.
